name: Continuous Delivery with DockerHub (Docker Actions)

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Java application
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build native with Maven
        run: mvn -B package
      - name: Upload jar for next job
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target
          retention-days: 1

  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Download jar from previous job
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d.%H%M%S')
        id: project
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/items:${{ steps.project.outputs.tag }}
